#!/usr/bin/env php
<?php

/**
 *
 * How to run:
 * php bin/console --help
 */

ob_start();

// -----

// Error displaying (comment the following to turn on error displaying)

error_reporting(0);

// Constants

define('ROOT_DIR', dirname(__FILE__));

// Imports

require_once 'lib/Autoloader.php';



// Run the app

$app = new Application;

$response = $app->run($argv);

$response->send();

// -----

ob_end_flush();
