#!/usr/bin/env php
<?php

/**
 *
 * How to run:
 * php console --help
 */

ob_start();

// -----

// Error displaying (comment the following to turn on error displaying)

error_reporting(0);

// Constants

define('ROOT_DIR', dirname(__FILE__));

// Imports

require_once 'lib/Autoloader.php';


// Run the app
try {

    $app = new Application;

    $response = $app->run($argv);

    $output = $response->output();

    echo $output . PHP_EOL;
} catch (\Throwable $th) {
    var_dump($th);
}

// -----

ob_end_flush();
